name: ci-app

on: push

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: make setup
      - run: make start
      - name: run tests
        run: make test
      - name: run linter
        run: make lint